apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: test
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: app-for-policy-repo
  name: sub-for-policy-repo
  namespace: policy-repo
spec:
  channel: policy-repo/channel-for-policy-repo
  placement:
    placementRef:
      kind: Placement
      name: placement-for-policy-repo    