apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: channel-for-app-policy-repo
  namespace: policy-repo
spec:
  type: Git
  pathname: 'https://github.com/rh-dluong/manage-fleet-configuration.git'  
