apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: app-for-policy-repo
  name: placement-for-app-policy-repo
  namespace: policy-repo
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
  clusterSets:
    - global
