apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: app-to-app 
    apps.open-cluster-management.io/git-path: deploy-to-global-hub
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: app-for-app-policy-repo
  name: sub-for-app-policy-repo
  namespace: policy-repo
spec:
  channel: policy-repo/channel-for-app-policy-repo
  placement:
    placementRef:
      kind: Placement
      name: placement-for-app-policy-repo    
